default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1234
  host: localhost

development:
  <<: *default
  database: watch_shop_development

test:
  <<: *default
  database: watch_shop_test
